import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/components/AppNavbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";

const joseFinSans = Josefin_Sans({

  subsets: ["latin"],
});



export const metadata = {
  title: "Mediqueue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    suppressHydrationWarning
      lang="en"
      className={`${joseFinSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          
          <AppNavbar />

          {children}

          <Footer />

          <Toaster />

        </ThemeProvider>
      </body>

      
    </html>
  );
}
