import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/components/AppNavbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const joseFinSans = Josefin_Sans({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${joseFinSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <AppNavbar/>
      {children}
      <Footer/>
      <Toaster/>
      </body>

      
    </html>
  );
}
